### ISSUE TITLE
Final Todo list 

### ISSUE THREAD

**Issue by PingWIN7** [muon-emergency/project-fob#42]
- [ ] Store user as a GUID
- [ ] Rename Fob model to topic
- [ ] Fix meeting crash in case of a second host connecting
- [ ] Rewrite some code so it can be tested
- [ ] Meeting topic change alert (Host and client side)
- [ ] Client clicked on button feedback

- [ ] Implement a way that a host user can be used to not allow anyone to shut down a meeting
